Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-09, with the labels that each got.

#5478 REDSHOP-6133 Support PHP 7.4
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/DiscountProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuestionManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/UserManagerJoomla3Steps.php
  tests/acceptance/integration/g09/Checkout_Quantity/CheckoutChangeQuantityProductCest.php
  tests/acceptance/integration/g16/Discounts/CouponVoucherMixCheckout/CouponVoucherMixCheckoutCest.php
Labels: 3.0.3, QA automation

#5461 DKSUP-483: redSHOP statistics
  component/admin/models/statistic_product.php
Labels: 3.0.3, Bug, Ready for Merge

#5475 REDSHOP-6127 Change html inline in function listAllUserFields to layout
  component/site/controllers/product.php
  libraries/redshop/layouts/extrafields/userfield/checkbox.php
  libraries/redshop/layouts/extrafields/userfield/document.php
  libraries/redshop/layouts/extrafields/userfield/image.php
  libraries/redshop/layouts/extrafields/userfield/multiple.php
  libraries/redshop/layouts/extrafields/userfield/radio.php
  libraries/redshop/layouts/extrafields/userfield/select.php
  libraries/redshop/layouts/extrafields/userfield/text.php
  libraries/redshop/layouts/extrafields/userfield/textarea.php
  libraries/redshop/src/Fields/SiteHelper.php
Labels: 3.0.3, Improve, Ready for Merge

#5479 REDSHOP-6086 Image error when user click on "Yes" in Watermark Manufacturer Image, Watermark Manufacturer thumb Image
  libraries/redshop/helper/media.php
  libraries/redshop/tags/sections/manufacturer.php
  libraries/redshop/tags/sections/manufacturerproduct.php
Labels: 3.0.3, Bug, Ready for Merge

#5480 REDSHOP-6137 Missing product user field in cart when reorder
  component/site/controllers/order_detail.php
  libraries/redshop/helper/product.php
  libraries/redshop/src/Order/Helper.php
Labels: 3.0.3, Bug, Ready for Merge

#5484 REDSHOP-6138 [Custom field] Validate type select, checkbox, radio doesn't allow user enter space in option value
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/field/tmpl/edit.php
  libraries/redshop/layouts/extrafields/userfield/image.php
  libraries/redshop/src/Fields/SiteHelper.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/shippingDefaultGLS.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
Labels: 3.0.3, Bug, Ready for Merge

#5485 REDSHOP-3974: Stockroom - Number of Minimum Stock Amount must be more than 0
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/models/stockroom.php
Labels: 3.0.3, Bug, Ready for Merge

#5472 REDSHOP-6130 Discount calculation double price when 2x click
  libraries/redshop/src/Promotion/Discount/Calculation.php
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
  tests/_support/Step/Traits/Delete.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutWithAjaxCart.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/TaxGroupSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/UserManagerJoomla3Steps.php
  tests/acceptance/administrator/g10/Products/Tax_Group/TaxGroupCest.php
  tests/acceptance/integration/g07/Promotion/PromotionsManagementCest.php
Labels: 3.0.3, Bug, Ready for Merge

#5489 REDSHOP-6142 Product attribute - Display Notice when user add stockroom attribute
  component/admin/views/product_detail/tmpl/productstockroom.php
  libraries/redshop/helper/stockroom.php
  media/com_redshop/js/ajaxupload.min.js
  media/com_redshop/js/media.min.js
  media/com_redshop/js/redshop.admin.common.min.js
  media/com_redshop/js/redshop.admin.min.js
  media/com_redshop/js/redshop.attribute-manipulation.min.js
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  media/com_redshop/js/redshop.common.min.js
  media/com_redshop/js/redshop.fields.min.js
  media/com_redshop/js/redshop.inline.min.js
  media/com_redshop/js/redshop.layout.min.js
  media/com_redshop/js/redshop.media.min.js
  media/com_redshop/js/redshop.order.min.js
  media/com_redshop/js/redshop.redbox.min.js
  media/com_redshop/js/redshop.registration.min.js
  media/com_redshop/js/redshop.search.min.js
  media/com_redshop/js/redshop.thumbscroller.min.js
  media/com_redshop/js/redshop.utils.min.js
  media/com_redshop/js/redshop.validation.min.js
  media/com_redshop/js/redshop.wishlist.min.js
  media/com_redshop/js/redshop.xmlfunc.min.js
  src/assets/com_redshop/js/redshop.attribute.js
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
Labels: 3.0.3, Bug, Ready for Merge

#5490 REDSHOP-6144 [Promotion] on some case
  component/admin/models/promotion.php
  plugins/redshop_promotion/promotion/language/en-GB/en-GB.plg_redshop_promotion_promotion.ini
  plugins/redshop_promotion/promotion/promotion.php
Labels: 3.0.3, Bug, Ready for Merge

#5492 REDSHOP-6145: Product does not use SEF url
  plugins/sh404sefextplugins/sh404sefextplugincom_redshop/redshop/sef.php
Labels: 3.0.3, Bug, Ready for Merge

#5488 REDSHOP-4342: Add user - Put requirement icon at some location
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/user_detail/tmpl/default_billing.php
  component/admin/views/user_detail/tmpl/default_user.php
Labels: 3.0.3, Bug, Ready for Merge

#5470 REDSHOP-6122: Create button clear infamation when reorder.
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/templates/template_tag.php
  component/admin/views/configuration/tmpl/default_cart_settings.php
  component/admin/views/configuration/view.html.php
  component/site/controllers/checkout.php
  component/site/language/en-GB/en-GB.com_redshop.ini
  component/site/models/checkout.php
  component/site/views/checkout/tmpl/default_address.php
  libraries/redshop/helper/js.php
  libraries/redshop/helper/user.php
  libraries/redshop/src/Config/App.php
  libraries/redshop/tags/sections/onestepcheckout.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  media/com_redshop/templates/onestep_checkout/default.php
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.3, Feature, Ready for Merge

#5494 REDSHOP-6148: [Hotfix] Move bootom stylesheet into check condition to prevent conflict bootstrap on client site
  component/site/layouts/assets.php
Labels: 3.0.3, Hot Fix

#5486 REDSHOP-3854: Show message when click on Cancel button
  component/admin/controllers/question.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
Labels: 3.0.3, Bug, Ready for Merge

#5495 [REDSHOP3.0.3] Fix wrong url action form registration
  libraries/redshop/src/IO/Route.php
Labels: 3.0.3, Bug, Ready for Merge

#5499 REDSHOP-6158 Can not send order mail to manufacturer and supplier
  libraries/redshop/src/Mail/Order.php
Labels: 3.0.3, Bug, Ready for Merge

#5500 REDSHOP-6153 [Automation] - Create CRUD + bad case Promotion
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/PromotionsManagementPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/PromotionsManagementSteps.php
  tests/acceptance/administrator/g02/Discount/Promotion/PromotionAdministratorCest.php
  tests/acceptance/integration/g07/Promotion/PromotionsManagementCest.php
Labels: QA automation
