Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-08, with the labels that each got.

#5428 REDSHOP-6043 Wrapping - Price show 0,00DKK in the cart
  libraries/redshop/src/Traits/Replace/CartItem.php
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/shippingDefaultGLS.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ShopperGroupManagerJoomla3Steps.php
Labels: 3.0.3, Bug, Ready for Merge, Scrutinizer fail

#5427 REDSHOP-3802 Order - Order detail - "Send Download Mail ' button working some things wrong
  component/admin/controllers/order_detail.php
Labels: 3.0.3, Bug, Ready for Merge

#5452 REDSHOP-6087 [#5442] Cart view - Remove Update quantity, update button (no longer need because of new ajax implementation)
  libraries/redshop/layouts/tags/cart/update_cart.html.twig
  media/com_redshop/templates/cart/default.php
  tests/_pages/Joomla3/Administrator/CheckoutChangeQuantityProductPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
Labels: 3.0.3, Drone fail, Improve, Wait for QA

#5441 REDSHOP-4104: REFACTOR: Stockroom
  component/admin/controllers/stockroom.php
  component/admin/controllers/stockroom_detail.php
  component/admin/controllers/stockrooms.php
  component/admin/helpers/xmlhelper.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/templates/template_tag.php
  component/admin/models/forms/filter_stockrooms.xml
  component/admin/models/forms/stockroom.xml
  component/admin/models/stockimage.php
  component/admin/models/stockimage_detail.php
  component/admin/models/stockroom.php
  component/admin/models/stockroom_detail.php
  component/admin/models/stockroom_listing.php
  component/admin/models/stockrooms.php
  component/admin/sql/install/mysql/data.sql
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.3.sql
  component/admin/tables/stockroom.php
  component/admin/tables/stockroom_detail.php
  component/admin/updates/3.0.3.php
  component/admin/views/configuration/view.html.php
  component/admin/views/order/tmpl/default.php
  component/admin/views/product_detail/tmpl/default_productstockroom.php
  component/admin/views/stockimage/tmpl/default.php
  component/admin/views/stockroom/tmpl/default.php
  component/admin/views/stockroom/tmpl/edit.php
  component/admin/views/stockroom/tmpl/importstock.php
  component/admin/views/stockroom/view.html.php
  component/admin/views/stockroom_detail/tmpl/default.php
  component/admin/views/stockroom_detail/view.html.php
  component/admin/views/stockroom_listing/tmpl/default.php
  component/admin/views/stockrooms/index.html
  component/admin/views/stockrooms/tmpl/default.php
  component/admin/views/stockrooms/tmpl/index.html
  component/admin/views/stockrooms/view.html.php
  component/site/layouts/product/stockroom_detail.php
  libraries/redshop/entity/stockroom.php
  libraries/redshop/helper/product.php
  libraries/redshop/helper/stockroom.php
  libraries/redshop/menu/left_menu.php
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/StockRoomManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ShopperGroupManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/StockRoomManagerJoomla3Steps.php
  tests/acceptance/administrator/g04/Stockrooms/StockRoom/StockRoomCest.php
Labels: 3.0.3, Ready for Merge, Refactor

#5454 REDSHOP-6097 Plugin GTM - Ecommerce for redSHOP
  gulp-extensions.json
  plugins/system/redgoogletagmanager/helper/google_tagmanager.php
  plugins/system/redgoogletagmanager/helper/index.html
  plugins/system/redgoogletagmanager/index.html
  plugins/system/redgoogletagmanager/language/en-GB/en-GB.plg_system_redgoogletagmanager.ini
  plugins/system/redgoogletagmanager/language/en-GB/en-GB.plg_system_redgoogletagmanager.sys.ini
  plugins/system/redgoogletagmanager/language/en-GB/index.html
  plugins/system/redgoogletagmanager/language/index.html
  plugins/system/redgoogletagmanager/redgoogletagmanager.php
  plugins/system/redgoogletagmanager/redgoogletagmanager.xml
  redGulp/extensions/plugins/system/redgoogletagmanager.js
  redGulp/src/main.js
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
Labels: 3.0.3, Feature, Ready for Merge

#5447 REDSHOP-6088 [#5443] Cart Module - Delete product not work
  modules/site/mod_redshop_cart/js/cart.js
Labels: 3.0.3, Bug, Ready for Merge

#5456 BEFR-755 - The link of image should be to Products page.
  libraries/redshop/layouts/tags/manufacturer/image.html.twig
  libraries/redshop/tags/sections/manufacturer.php
Labels: 3.0.3, Bug, Ready for Merge

#5436 REDSHOP-4110: REFACTOR: Wrapper
  component/admin/controllers/wrapper.php
  component/admin/controllers/wrapper_detail.php
  component/admin/controllers/wrappers.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/wrapper/image.php
  component/admin/models/forms/filter_wrappers.xml
  component/admin/models/forms/wrapper.xml
  component/admin/models/wrapper.php
  component/admin/models/wrapper_detail.php
  component/admin/models/wrappers.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.3.sql
  component/admin/tables/wrapper.php
  component/admin/tables/wrapper_detail.php
  component/admin/updates/3.0.3.php
  component/admin/views/order_detail/tmpl/default.php
  component/admin/views/wrapper/tmpl/default.php
  component/admin/views/wrapper/tmpl/edit.php
  component/admin/views/wrapper/view.html.php
  component/admin/views/wrapper_detail/tmpl/default.php
  component/admin/views/wrapper_detail/view.html.php
  component/admin/views/wrappers/index.html
  component/admin/views/wrappers/tmpl/default.php
  component/admin/views/wrappers/tmpl/index.html
  component/admin/views/wrappers/view.html.php
  libraries/redshop/entity/wrapper.php
  libraries/redshop/helper/product.php
  libraries/redshop/menu/left_menu.php
  libraries/redshop/src/Economic/RedshopEconomic.php
  libraries/redshop/src/Order/Item.php
  libraries/redshop/src/Traits/Replace/CartItem.php
  libraries/redshop/src/Wrapper/Helper.php
  libraries/redshop/tags/sections/wrapper.php
  tests/_pages/Joomla3/Administrator/WrapperPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/WrapperSteps.php
  tests/acceptance/administrator/g04/Shippings/Wrapper/WrapperCest.php
Labels: 3.0.3, Ready for Merge, Refactor

#5457 REDSHOP-6100 Show error when user click on "link download" in Download Mail
  component/admin/controllers/xmlexport_detail.php
  component/site/controllers/product.php
  component/site/views/product/tmpl/downloadproduct.php
  libraries/redshop/html/redshopmedia.php
Labels: 3.0.3, Bug, Ready for Merge

#5450 REDSHOP-6085 [#5438] Product attribute > Attribute value price save error
  component/admin/tables/attributeprices_detail.php
  libraries/redshop/src/Attribute/Helper.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/shippingDefaultGLS.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
Labels: 3.0.3, Bug, Ready for Merge

#5433 REDSHOP-5922 [Bug] Can not send invoice mail.
  plugins/redshop_pdf/tcpdf/tcpdf.php
Labels: 3.0.3, Bug, Ready for Merge

#5430 REDSHOP-6076: Not send email when user submit catalog
  component/site/controllers/catalog.php
  libraries/redshop/src/Mail/Catalog.php
Labels: 3.0.3, Bug, Ready for Merge, Scrutinizer fail

#5431 REDSHOP-5810 Quotation - Exclude VAT in Quotation Total
  media/com_redshop/js/redshop.admin.common.js
  media/com_redshop/js/redshop.admin.common.min.js
  src/assets/com_redshop/js/redshop.admin.common.js
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
Labels: 3.0.3, Bug, Ready for Merge

#5455 BEFR-730: libraries/redshop/src/Statistic/Helper.php
  libraries/redshop/src/Statistic/Helper.php
Labels: 3.0.3, Bug, Ready for Merge

#5444 REDSHOP-6091: [Bug] Must apply VAT when user not login when default apply VAT for group in redSHOP Config, and excluding VAT when login user company in checkout page (shopper group preset without VAT)
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/tables/tax_rate.php
  component/admin/views/tax_rates/view.html.php
  libraries/redshop/helper/tax.php
  libraries/redshop/helper/user.php
  libraries/redshop/src/Template/Helper.php
Labels: 3.0.3, Bug, Ready for Merge

#5458 REDSHOP-6107 Save time on drone server
  .drone.yml
  tests/_pages/Joomla3/Administrator/ConfigurationPage.php
  tests/_pages/Joomla3/Administrator/QuestionManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/AdminManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuestionManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
  tests/acceptance/integration/g10/Discounts/GiftCardCheckout/GiftCardCheckoutProductCest.php
  tests/acceptance/integration/g15/Ajax/OnePageCheckoutWithCartAjaxCest.php
  tests/acceptance/integration/g15/Missing/OnePageCheckoutMissingDataCest.php
  tests/acceptance/integration/g15/OneStepCheckout/OnePageCheckoutCest.php
Labels: 3.0.3, QA automation

#5460 REDSHOP-6109 Product discount does not display if we do not set start date and end date
  libraries/redshop/helper/discount.php
Labels: 3.0.3, Bug, Ready for Merge

#5465 REDSHOP-6075 [Codeception] - Wrapping
  .drone.yml
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ManufacturerSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/integration/g02/Manufacturer/CheckoutProductInManufacturerDetailCest.php
  tests/acceptance/integration/g04/Shipping/Wrapping/WrappingFrontEndCest.php
  tests/acceptance/integration/g17/Module/ModuleProductRelatedCest.php
Labels: 3.0.3, QA automation

#5464 REDSHOP-6112 Fix miss layout newsletter statistics
  component/admin/views/newsletter/tmpl/statistics.php
  component/admin/views/newsletter/view.html.php
  libraries/redshop/menu/left_menu.php
  libraries/redshop/src/Newsletter/Helper.php
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
  tests/acceptance/integration/g02/Manufacturer/CheckoutProductInManufacturerDetailCest.php
Labels: 3.0.3, Bug, Ready for Merge

#5459 REDSHOP-4091: REFACTOR: Newsletter Subscrible
  component/admin/controllers/newsletter_subscription.php
  component/admin/controllers/newsletter_subscriptions.php
  component/admin/controllers/newslettersubscr.php
  component/admin/controllers/newslettersubscr_detail.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/models/forms/filter_newsletter_subscriptions.xml
  component/admin/models/forms/newsletter_subscription.xml
  component/admin/models/newsletter_subscription.php
  component/admin/models/newsletter_subscriptions.php
  component/admin/models/newsletters.php
  component/admin/models/newslettersubscr.php
  component/admin/models/newslettersubscr_detail.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.3.sql
  component/admin/tables/newsletter_subscription.php
  component/admin/tables/newslettersubscr_detail.php
  component/admin/updates/3.0.3.php
  component/admin/views/newsletter_subscription/index.html
  component/admin/views/newsletter_subscription/tmpl/edit.php
  component/admin/views/newsletter_subscription/tmpl/index.html
  component/admin/views/newsletter_subscription/view.html.php
  component/admin/views/newsletter_subscriptions/index.html
  component/admin/views/newsletter_subscriptions/tmpl/default.php
  component/admin/views/newsletter_subscriptions/tmpl/index.html
  component/admin/views/newsletter_subscriptions/view.html.php
  component/admin/views/newsletters/tmpl/preview.php
  component/admin/views/newslettersubscr/tmpl/default.php
  component/admin/views/newslettersubscr/view.html.php
  component/admin/views/newslettersubscr_detail/tmpl/default.php
  component/admin/views/newslettersubscr_detail/view.html.php
  component/site/models/checkout.php
  component/site/models/newsletter.php
  libraries/redshop/entity/newsletter_subscription.php
  libraries/redshop/form/field/newsletter.php
  libraries/redshop/form/fields/newslettersubscriberuser.php
  libraries/redshop/helper/newsletter.php
  libraries/redshop/menu/left_menu.php
  libraries/redshop/src/Mail/Newsletter.php
  libraries/redshop/src/Traits/Replace/NewsletterSubscription.php
Labels: 3.0.3, Ready for Merge, Refactor

#5440 REDSHOP-6081 Orderby is not showed and filter option shouldn't when product discountinued
  component/site/views/category/view.html.php
Labels: 3.0.3, Bug, Ready for Merge

#5469 REDSHOP-6115 Lightweight size of redSHOP release installation.
  component/site/views/login/tmpl/default.php
  libraries/redshop/composer.json
  libraries/redshop/layouts/tags/checkout/onestep/login.html.twig
  libraries/redshop/layouts/tags/login/form.html.twig
  libraries/redshop/src/Helper/Login.php
  libraries/redshop/tags/sections/login.php
  libraries/redshop/tags/sections/onestepcheckout.php
  modules/site/mod_redshop_login/helper.php
  modules/site/mod_redshop_login/language/en-GB/en-GB.mod_redshop_login.ini
  modules/site/mod_redshop_login/language/en-GB/en-GB.mod_redshop_login.sys.ini
  modules/site/mod_redshop_login/mod_redshop_login.php
  modules/site/mod_redshop_login/mod_redshop_login.xml
  modules/site/mod_redshop_login/tmpl/default.php
  modules/site/mod_redshop_switch_vat/css/index.html
  modules/site/mod_redshop_switch_vat/helper.php
  modules/site/mod_redshop_switch_vat/images/index.html
  modules/site/mod_redshop_switch_vat/index.html
  modules/site/mod_redshop_switch_vat/js/default.js
  modules/site/mod_redshop_switch_vat/js/index.html
  modules/site/mod_redshop_switch_vat/language/en-GB/en-GB.mod_redshop_switch_vat.ini
  modules/site/mod_redshop_switch_vat/language/en-GB/en-GB.mod_redshop_switch_vat.sys.ini
  modules/site/mod_redshop_switch_vat/language/en-GB/index.html
  modules/site/mod_redshop_switch_vat/language/index.html
  modules/site/mod_redshop_switch_vat/mod_redshop_switch_vat.php
  modules/site/mod_redshop_switch_vat/mod_redshop_switch_vat.xml
  modules/site/mod_redshop_switch_vat/tmpl/default.php
  modules/site/mod_redshop_switch_vat/tmpl/index.html
  plugins/redshop_login/facebook/facebook.php
  plugins/redshop_login/facebook/facebook.xml
  plugins/redshop_login/facebook/index.html
  plugins/redshop_login/facebook/language/en-GB/en-GB.plg_redshop_login_facebook.ini
  plugins/redshop_login/facebook/language/en-GB/en-GB.plg_redshop_login_facebook.sys.ini
  plugins/redshop_login/facebook/library/composer.json
  plugins/redshop_login/google/google.php
  plugins/redshop_login/google/google.xml
  plugins/redshop_login/google/index.html
  plugins/redshop_login/google/language/en-GB/en-GB.plg_redshop_login_google.ini
  plugins/redshop_login/google/language/en-GB/en-GB.plg_redshop_login_google.sys.ini
  plugins/redshop_login/google/library/composer.json
  redGulp/extensions/modules/frontend/redshop_switch_vat.js
  redGulp/extensions/plugins/redshop_login/facebook.js
  redGulp/extensions/plugins/redshop_login/google.js
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuestionManagerJoomla3Steps.php
Labels: 3.0.3, Improve, Ready for Merge

#5471 REDSHOP-6123 [Bug] Stockroom enable with option Set Stock As Infinitive work incorrect, counter never set to 0.
  libraries/redshop/helper/stockroom.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
Labels: 3.0.3, Bug, Ready for Merge

#5473 REDSHOP-6128 Update joomla version 3.9.21 for redSHOP
  RoboFile.php
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/payment/CheckoutWithEWAYPayment.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/UserManagerJoomla3Steps.php
  tests/acceptance/administrator/g03/Notices/FrontEndNoticesCest.php
  tests/acceptance/administrator/g03/Notices/NoticesCest.php
  tests/acceptance/administrator/g16/Product_Price_Discount/ProductPriceDiscountCest.php
  tests/acceptance/integration/g17/Plugins/payment/ProductsCheckoutBankTransferDiscountCest.php
Labels: QA automation

#5476 REDSHOP-6132: Default sorting should be ID descending
  component/admin/models/manufacturers.php
Labels: 3.0.3, Ready for Merge

#5384 REDSHOP-6016: Message inform wrong for discount total.
  component/site/language/en-GB/en-GB.com_redshop.ini
  libraries/redshop/helper/discount.php
  libraries/redshop/tags/sections/cart.php
Labels: 3.0.3, Bug

#5474 REDSHOP-6129: [Bug] Promotions issue with ajax cart box
  libraries/redshop/helper/discount.php
  libraries/redshop/src/Cart/Ajax.php
  libraries/redshop/src/Workflow/Accessory.php
  libraries/redshop/src/Workflow/Cart.php
  libraries/redshop/src/Workflow/Cart/Add.php
  plugins/redshop_promotion/promotion/helpers/Helper.php
  plugins/redshop_promotion/promotion/helpers/Step.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuestionManagerJoomla3Steps.php
Labels: 3.0.3, Bug, Drone fail, Wait for QA

#5468 REDSHOP-6113 Custom field section category does not replace if option "show in front" is no
  libraries/redshop/tags/sections/categorydetail.php
Labels: 3.0.3, Bug, Ready for Merge
