Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-07, with the labels that each got.

#5395 REDSHOP-6030 Question - Message after click on "Send", "Delete" wrong when user not select Answer
  component/admin/views/question/tmpl/edit.php
Labels: 3.0.2, Bug, Ready for Merge

#5396 REDSHOP-6037 Product accessory - disable product when discontinued
  libraries/redshop/helper/accessory.php
  libraries/redshop/layouts/tags/accessory/add_chkbox.html.twig
  libraries/redshop/tags/sections/accessory.php
Labels: 3.0.2, Bug, Ready for Merge

#5397 REDSHOP-6035 Codeception - Checkout with product in Manufacturer detail
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/ManufacturerPage.php
  tests/_pages/Joomla3/Administrator/ProductManagerPage.php
  tests/_support/Step/Traits/Delete.php
  tests/acceptance/administrator/_steps/Joomla3Steps/AdminManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/payment/CheckoutWithEANTransferPayment.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ManufacturerSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/integration/g02/Manufacturer/CheckoutProductInManufacturerDetailCest.php
Labels: QA automation

#5398 REDSHOP-6034 Codeception - Product discountinued will no display on list product accessory
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/Administrator/ProductManagerPage.php
  tests/_support/Step/Traits/Delete.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ProductsConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Module/ModuleProductRelatedSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/g16/Products/ProductDiscountinued/ProductAccessoriesDiscountinuedCest.php
Labels: QA automation

#5359 REDSHOP-5980: Product review sorting, newest first
  libraries/redshop/helper/product.php
Labels: 3.0.2, Bug, Drone fail, External, Ready for Merge

#5400 REDSHOP-6038 [Bug] Template product has tag {without_vat} but tag {product_price_table} still show price include VAT
  component/site/layouts/product/product_price_table.php
  libraries/redshop/helper/product.php
  libraries/redshop/helper/product/price.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/shippingDefaultGLS.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/payment/CheckoutWithKlarnaPayment.php
Labels: 3.0.2, Bug, Ready for Merge

#5401 REDSHOP-6039 [Reractor][Component][Site] Move to use Twig for view Account shipto
  component/site/views/account_billto/view.html.php
  component/site/views/account_shipto/tmpl/default.html.twig
  component/site/views/account_shipto/tmpl/default.php
  component/site/views/account_shipto/tmpl/form.html.twig
  component/site/views/account_shipto/tmpl/form.php
  component/site/views/account_shipto/view.html.php
  media/com_redshop/js/account/shipto.js
  media/com_redshop/js/account/shipto.min.js
  src/assets/com_redshop/js/account/shipto.js
Labels: 3.0.2, Ready for Merge, Refactor

#5399 REDSHOP-6029 Lost image product after crop image and 'Save' it
  component/admin/models/product_detail.php
Labels: 3.0.2, Bug, Ready for Merge

#5404 Update README.md
  README.md
Labels: 3.0.2, Document

#5403 REDSHOP-5642 Product detail - Out of stock product even though stock functionality is disabled inside Redshop configuration
  libraries/redshop/src/Helper/Stockroom.php
Labels: 3.0.2, Bug, Ready for Merge

#5405 remove quotation marks
  libraries/redshop/layouts/tags/category_product/hidden_user_field.html.twig
Labels: 3.0.2, Hot Fix, Ready for Merge

#5385 REDSHOP-5667 [Bug] When we delete products having the same id with category, user... It will delete custom fields of that category, user ... too
  component/admin/models/product_detail.php
Labels: 3.0.2, Bug, Ready for Merge, Reopened

#5402 REDSHOP-6041 [Twig] Move twig core to a plugin
  .drone.yml
  libraries/redshop/composer.json
  libraries/redshop/library.php
  libraries/redshop/redshop.xml
  plugins/system/redshop/language/en-GB/en-GB.plg_system_redshop.ini
  plugins/system/redshop/libraries/composer.json
  plugins/system/redshop/redshop.xml
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/shippingDefaultGLS.php
  tests/acceptance/integration/g17/Plugins/Shipping/shippingBusinessGLSCest.php
Labels: 3.0.2, Improve, Ready for Merge

#5412 Bump version 3.0.2
  RoboFile.php
  component/admin/models/categories.php
  component/admin/models/manufacturers.php
  component/admin/views/order_statuses/view.html.php
  libraries/redshop/src/Order/Helper.php
  libraries/redshop/src/User/Helper.php
Labels: 3.0.2, Bump Version

#5416 REDSHOP-6055 Support fix fail Drone for redSHOP
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/shippingDefaultGLS.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/install/core/InstallRedShopCest.php
Labels: QA automation, Ready for Merge

#5407 REDSHOP-6046 [cart] - Broken layout page cart when press key Enter at field input voucher
  libraries/redshop/layouts/tags/cart/discount_form.html.twig
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.3, Bug, Ready for Merge

#5277 REDSHOP-5938: Add to cart error with userfield "file upload"
  libraries/redshop/layouts/tags/addtocart/template.html.twig
  libraries/redshop/src/Cart/Render.php
  libraries/redshop/src/User/Helper.php
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.3, Bug, Ready for Merge

#5386 REDSHOP-6023 Discount calculator don't output price in {product_price_novat} with Product default price = 0
  libraries/redshop/helper/product/price.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingPostDanmark.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
Labels: 3.0.3, Bug, Ready for Merge

#5406 REDSHOP-4379 Product detail - Add Price - add "Close" button on "Add price" page
  component/admin/controllers/prices.php
  component/admin/views/prices/view.html.php
Labels: 3.0.3, Improve, Ready for Merge

#5419 REDSHOP-4097 REFACTOR: Sample
  component/admin/controllers/sample.php
  component/admin/controllers/sample_detail.php
  component/admin/controllers/samples.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/sample/catalog_color.php
  component/admin/models/forms/filter_samples.xml
  component/admin/models/forms/sample.xml
  component/admin/models/sample.php
  component/admin/models/sample_detail.php
  component/admin/models/samples.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.3.sql
  component/admin/tables/sample.php
  component/admin/tables/sample_detail.php
  component/admin/views/sample/tmpl/default.php
  component/admin/views/sample/tmpl/edit.php
  component/admin/views/sample/view.html.php
  component/admin/views/sample_detail/tmpl/default.php
  component/admin/views/sample_detail/view.html.php
  component/admin/views/samples/index.html
  component/admin/views/samples/tmpl/default.php
  component/admin/views/samples/tmpl/index.html
  component/admin/views/samples/view.html.php
  libraries/redshop/menu/left_menu.php
  redshop.xml
Labels: 3.0.3, Ready for Merge, Refactor

#5417 REDSHOP-6045 [redSHOP] [Plugin Config] New view for centralize manage redshop plugin config
  component/admin/controllers/plugins.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/view/list.php
  component/admin/models/forms/filter_plugins.xml
  component/admin/models/forms/plugin.xml
  component/admin/models/plugins.php
  component/admin/views/plugins/index.html
  component/admin/views/plugins/tmpl/default.php
  component/admin/views/plugins/tmpl/default_modal.php
  component/admin/views/plugins/tmpl/index.html
  component/admin/views/plugins/view.html.php
  libraries/redshop/menu/left_menu.php
  libraries/redshop/view/list.php
  media/com_redshop/css/redshop.admin.css
  media/com_redshop/css/redshop.admin.min.css
Labels: 3.0.3, Feature, Ready for Merge, Scrutinizer fail

#5420 REDSHOP-3455 REFACTOR: Rating
  component/admin/controllers/rating.php
  component/admin/controllers/rating_detail.php
  component/admin/controllers/ratings.php
  component/admin/layouts/rating/star_rating.php
  component/admin/models/forms/filter_ratings.xml
  component/admin/models/forms/rating.xml
  component/admin/models/rating.php
  component/admin/models/rating_detail.php
  component/admin/models/ratings.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.3.sql
  component/admin/tables/rating.php
  component/admin/tables/rating_detail.php
  component/admin/updates/3.0.3.php
  component/admin/views/plugins/tmpl/default_modal.php
  component/admin/views/rating/tmpl/default.php
  component/admin/views/rating/tmpl/edit.php
  component/admin/views/rating/view.html.php
  component/admin/views/rating_detail/index.html
  component/admin/views/rating_detail/tmpl/default.php
  component/admin/views/rating_detail/tmpl/index.html
  component/admin/views/rating_detail/view.html.php
  component/admin/views/ratings/index.html
  component/admin/views/ratings/tmpl/default.php
  component/admin/views/ratings/tmpl/index.html
  component/admin/views/ratings/view.html.php
  component/site/models/product.php
  component/site/models/product_rating.php
  libraries/redshop/entity/rating.php
  libraries/redshop/helper/product.php
  libraries/redshop/layouts/product/rating_comments.php
  libraries/redshop/layouts/tags/review/images.html.twig
  libraries/redshop/menu/left_menu.php
  libraries/redshop/src/Demo/Install.php
  libraries/redshop/src/Product/Product.php
  libraries/redshop/src/Rating/Helper.php
  tests/_pages/Joomla3/Administrator/RatingManagerPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
Labels: 3.0.3, Ready for Merge, Refactor, Scrutinizer fail

#5418 REDSHOP-3626 Order Management - Orders detail - Special discount Can't over 100%
  component/admin/controllers/addorder_detail.php
Labels: 3.0.3, Bug, Ready for Merge

#5414 REDSHOP-6022 Use for all products not work in list page
  component/admin/controllers/wrapper.php
  libraries/redshop/src/Wrapper/Helper.php
Labels: 3.0.3, Drone fail, Ready for Merge

#5410 REDSHOP-6026 Text Library - "Description" in list item work wrong
  component/admin/models/texts.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
Labels: 3.0.3, Bug, Ready for Merge

#5421 REDSHOP-6064 Add Price - The field does not accept decimal values
  component/admin/views/prices_detail/tmpl/default.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
Labels: 3.0.3, Bug, Ready for Merge

#5408 REDSHOP-4355 Product detail page - Remove stock_status if the product is "Product Discontinued" or "Product not for sell"
  libraries/redshop/src/Helper/Stockroom.php
Labels: 3.0.3, Bug, Ready for Merge

#5423 REDSHOP-4100 REFACTOR: Shipping
  component/admin/controllers/shipping.php
  component/admin/controllers/shipping_detail.php
  component/admin/controllers/shipping_method.php
  component/admin/controllers/shipping_methods.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/shipping/shipping_config.php
  component/admin/layouts/shipping/shipping_method.php
  component/admin/layouts/view/edit/box.php
  component/admin/layouts/view/list.php
  component/admin/models/forms/shipping_method.xml
  component/admin/models/shipping.php
  component/admin/models/shipping_detail.php
  component/admin/models/shipping_method.php
  component/admin/models/shipping_methods.php
  component/admin/updates/3.0.3.php
  component/admin/views/shipping/tmpl/default.php
  component/admin/views/shipping/tmpl/index.html
  component/admin/views/shipping/view.html.php
  component/admin/views/shipping_detail/tmpl/default.php
  component/admin/views/shipping_detail/tmpl/default_install.php
  component/admin/views/shipping_detail/tmpl/index.html
  component/admin/views/shipping_detail/view.html.php
  component/admin/views/shipping_method/index.html
  component/admin/views/shipping_method/tmpl/edit.php
  component/admin/views/shipping_method/tmpl/index.html
  component/admin/views/shipping_method/view.html.php
  component/admin/views/shipping_methods/index.html
  component/admin/views/shipping_methods/tmpl/default.php
  component/admin/views/shipping_methods/tmpl/index.html
  component/admin/views/shipping_methods/view.html.php
  libraries/redshop/menu/left_menu.php
  libraries/redshop/view/list.php
  tests/_pages/Joomla3/Administrator/ShippingPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ShippingSteps.php
Labels: 3.0.3, Ready for Merge, Refactor, Scrutinizer fail

#5409 REDSHOP-5527 Statistic - Newest Order show page not working (with bulk orders)
  component/admin/models/statistic.php
Labels: 3.0.3, Bug, Ready for Merge

#5411 REDSHOP-5983 [Rating Management] - Check all result only work with item first
  libraries/redshop/src/Rating/Helper.php
Labels: 3.0.3, Bug, Ready for Merge

#5415 REDSHOP-5880 Custom Field type Date Picker have problem when appear on front-end
  libraries/redshop/html/redshopcalendar.php
  libraries/redshop/src/Fields/SiteHelper.php
  media/com_redshop/css/redshop.admin.css
  media/com_redshop/css/redshop.admin.min.css
Labels: 3.0.3, Ready for Merge

#5435 REDSHOP-6078 Can not gulp copy files redshop.xml and install.php
  redGulp/extensions/components/redshop.js
Labels: 3.0.3, Hot Fix, Merged

#5439 REDSHOP-6077 Update joomla version 3.9.20 for redSHOP
  RoboFile.php
Labels: QA automation

#5429 Fix display product out of stock after
  component/site/models/category.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuestionManagerJoomla3Steps.php
Labels: 3.0.3, Improve, Ready for Merge

#5426 Add action for form order by
  libraries/redshop/layouts/tags/category/orderby_form.html.twig
  libraries/redshop/tags/sections/categorydetail.php
Labels: 3.0.3, Bug, Ready for Merge

#5432 REDSHOP-6069 Webpage show product in product after choose Discontinue Product is Yes
  libraries/redshop/src/Cart/Render.php
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.3, Bug, Ready for Merge, Scrutinizer fail

#5446 REDSHOP-6095 Default sorting in custom fields list (backend) should be ID desc
  component/admin/models/fields.php
Labels: 3.0.3, Improve

#5448 REDSHOP-6087 [#5442] Cart Module - Delete product from cart does not update instantly, need to refresh page
  libraries/redshop/layouts/tags/cart/update_cart.html.twig
  media/com_redshop/templates/cart/default.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/g15/Product_Price/AddProductPriceCest.php
Labels: 3.0.3, Improve

#5451 Revert "EDSHOP-6087 [#5442] Cart view - Remove Update quantity, update button (no longer need because of new ajax implementation)"
  libraries/redshop/layouts/tags/cart/update_cart.html.twig
  media/com_redshop/templates/cart/default.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/g15/Product_Price/AddProductPriceCest.php
Labels: 3.0.3

#5453 REDSHOP-6036 [Bug] Show tag {companyname} and {companyname_lbl} if user is not company
  libraries/redshop/src/Shipping/Tag.php
Labels: 3.0.3, Bug, Ready for Merge
