Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-06, with the labels that each got.

#5353 REDSHOP-5989 VAT for EU-mode
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/Administrator/TaxRatePage.php
  tests/_pages/Joomla3/Administrator/UserManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/TaxRateSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/UserManagerJoomla3Steps.php
  tests/acceptance/integration/g10/Products/ProductsCheckoutFrontEndCest.php
  tests/acceptance/integration/g13/VAT_EU_Mode/CheckVATWithUserMultiGroupCest.php
  tests/acceptance/integration/g17/Plugins/payment/Products2CheckoutCest.php
Labels: QA automation

#5344 [Hot fix] Clearly if condition that better.
  modules/site/mod_redshop_search/tmpl/default.html.twig
Labels: 3.0.2, Hot Fix, Merged

#5347 HOD-287: Update registration email
  libraries/redshop/src/Mail/User.php
Labels: 3.0.2, Hot Fix, Merged

#5350 Fix checked payment method view checkout
  libraries/redshop/tags/sections/paymentmethod.php
Labels: 3.0.2, Hot Fix, Merged

#5352 TL-130 Fix order when filter category
  component/site/models/category.php
Labels: 3.0.2, Bug, Merged

#5357 REDSHOP-5602 Create automated test for Post Danmark
  .drone.yml
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/System/PluginManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Administrator/plugins/PluginPaymentManagerJoomla.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingPostDanmark.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/integration/g17/Plugins/Shipping/shippingPostDanmarkCest.php
Labels: QA automation

#5364 Add encr_key for link order detail in mail payment method change
  libraries/redshop/layouts/email/order/payment_method_changed.php
  libraries/redshop/src/Order/Helper.php
Labels: 3.0.2, Improve, Merged

#5355 TL-134 Fix not show popup select attribute and select2 not work on fi…
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
Labels: 3.0.2, Hot Fix, Issue Inprocess

#5356 SP-42: Add condition search fields data in module redshop search
  component/site/models/search.php
  modules/site/mod_redshop_search/language/en-GB/en-GB.mod_redshop_search.ini
  modules/site/mod_redshop_search/mod_redshop_search.php
  modules/site/mod_redshop_search/mod_redshop_search.xml
  modules/site/mod_redshop_search/tmpl/default.html.twig
Labels: 3.0.2, Improve, Ready for Merge

#5343 REDSHOP-5990 Error show tag out frontend in page search
  component/site/views/search/tmpl/default.php
  component/site/views/search/view.html.php
Labels: 3.0.2, Bug, Ready for Merge

#5348 REDSHOP-5724 Missing image after user click on 'Save as Copy' button
  component/admin/models/product_detail.php
Labels: 3.0.2, Bug, Ready for Merge

#5354 SWD-257 Don't get 'Leg Colour' label when user not select in Product detail
  libraries/redshop/src/Cart/Helper.php
Labels: 3.0.2, Bug, Merged

#5365 TL-135 Fix module filter product can not unchecked checkbox when has one checked checkbox
  component/site/models/category.php
Labels: 3.0.2, Hot Fix, Merged

#5367 REDSHOP-5712 Change text [Edit] to [New] when create new
  component/admin/views/order_status/view.html.php
Labels: 3.0.2, Hot Fix, Merged

#5366 Fix filter product custom field not work
  libraries/redshop/helper/category.php
Labels: 3.0.2, Bug, Ready for Merge

#5370 Fix call function php from twig
  libraries/redshop/src/Extension/Redshop.php
Labels: 3.0.2, Hot Fix, Merged

#5371 SWD-244 Add username to order log, reformat log timestamp, clean up code of logging order
  component/admin/models/addorder_detail.php
  component/admin/models/quotation_detail.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.2.sql
  component/admin/views/order_detail/tmpl/default.php
  component/site/models/checkout.php
  libraries/redshop/helper/order.php
Labels: 3.0.2, Improve, Ready for Merge

#5375 Remove div
  component/site/redshop.php
Labels: 3.0.2, Hot Fix, Ready for Merge

#5368 REDSHOP-5955 Support automation stable on redSHOP
  .drone.yml
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/Administrator/UserManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingPostDanmark.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/UserManagerJoomla3Steps.php
  tests/acceptance/integration/g17/Plugins/Shipping/shippingPostDanmarkCest.php
Labels: QA automation

#5379 REDSHOP-5706 Add tooltip desc published
  component/admin/models/forms/tax_group.xml
Labels: 3.0.2, Improve, Ready for Merge

#5377 REDSHOP-5722 Show warning when user add product compare
  component/site/layouts/product/compare_ajax.php
Labels: 3.0.2, Bug, Ready for Merge

#5363 REDSHOP-5936: Admin > Coupon > Add new > User specific = slow loading list
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/models/forms/coupon.xml
  component/admin/models/forms/field.xml
  component/admin/models/search.php
  component/admin/sql/updates/mysql/3.0.2.sql
  component/admin/views/coupon/view.html.php
  component/admin/views/field/tmpl/edit.php
  component/site/models/checkout.php
  libraries/redshop/form/field/coupon_remaining.php
  libraries/redshop/form/field/coupon_user.php
  libraries/redshop/helper/cart/discount.php
Labels: 3.0.2, Bug, Ready for Merge

#5380 SP-68: View all button not show all product
  component/site/models/category.php
Labels: 3.0.2, Bug, Ready for Merge

#5376 TL-141 [Page checkout] scroll top when validate error
  media/com_redshop/js/redshop.registration.js
  media/com_redshop/js/redshop.registration.min.js
  src/assets/com_redshop/js/redshop.registration.js
Labels: 3.0.2, Improve, Ready for Merge

#5374 TL-139 Fix button add cart no disappears when product out of stock
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
Labels: 3.0.2, Bug, Ready for Merge

#5372 REDSHOP-6007: Checkout validation terms condition don't work with existing user
  libraries/redshop/src/Traits/Replace/TermsConditions.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.2, Bug, Ready for Merge

#5378 REDSHOP-5704 Wrong when user fill in quantity is string
  component/admin/views/product_detail/tmpl/default_productstockroom.php
  component/admin/views/product_detail/tmpl/productstockroom.php
Labels: 3.0.2, Bug, Ready for Merge

#5381 REDSHOP-6009 Codeception - Checkout validation terms condition don't work with existing user
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/ConfigurationPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/install/extension/InstallRedSHOPPaidExtensionsCest.php
  tests/acceptance/integration/g15/TermsCondition/CheckoutValidationTermsConditionCest.php
Labels: QA automation

#5361 REDSHOP-5949: Admin > Order detail view > Update discount error
  component/admin/controllers/order_detail.php
Labels: 3.0.2, Bug, External, Ready for Merge

#5382 REDSHOP-6018 Fix no change price when checkboxed accessory
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
Labels: 3.0.2, Bug, Wait for QA

#5383 REDSHOP-6019 add feature to allow configure order of order status
  component/admin/models/order_statuses.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/updates/mysql/3.0.2.sql
  component/admin/views/order_statuses/view.html.php
  libraries/redshop/helper/order.php
Labels: 3.0.2, Improve, Ready for Merge

#5387 REDSHOP-6024 Lost fields Height, Width, Length in {discount_calculator}
  component/site/views/product/tmpl/default_calculator.php
Labels: 3.0.2, Bug, Ready for Merge

#5389 REDSHOP-6027 [Account billto] Missing value mail confirm when edit account billing
  libraries/redshop/tags/sections/commonfield.php
Labels: 3.0.2, Bug, Ready for Merge

#5388 REDSHOP-6025 Add to cart. No selected attribute error message
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
Labels: 3.0.2, Bug, Ready for Merge

#5373 BEFR-515 Fix wrong md5 key payment paypal
  libraries/redshop/helper/order.php
  modules/site/mod_redshop_cart/mod_redshop_cart.php
  plugins/redshop_payment/rs_payment_paypal/rs_payment_paypal.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingGiaoHangNhanh.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
Labels: 3.0.2, Bug, Ready for Merge

#5390 REDSHOP-6021 button PAY not work when click link in mail update payment method
  component/site/controllers/order_detail.php
  component/site/views/order_detail/tmpl/checkout_final.php
  component/site/views/order_detail/view.html.php
Labels: 3.0.2, Bug, Ready for Merge

#5391 REDSHOP-5861 Fix show full image when crop image
  media/com_redshop/js/redshop.media.js
  media/com_redshop/js/redshop.media.min.js
  src/assets/com_redshop/js/redshop.media.js
Labels: 3.0.2, Bug, Ready for Merge

#5392 REDSHOP-6033 Product discountinued will no display on list product accessory
  libraries/redshop/helper/accessory.php
  libraries/redshop/tags/sections/accessory.php
Labels: 3.0.2, Bug, Ready for Merge
