Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-12, with the labels that each got.

#5533 REDSHOP-6139 Frontend page show Option Value
  libraries/redshop/layouts/extrafields/userfield/checkbox.php
  libraries/redshop/layouts/extrafields/userfield/radio.php
Labels: 3.0.3, Bug, Wait for QA

#5529 REDSHOP-6141 Mail Management - Filter item incorrect
  component/admin/models/mails.php
Labels: 3.0.3, Bug, Ready for Merge

#5535 REDSHOP-6020: Shipping box Creation - Wrong header text when on new item page
  component/admin/views/shipping_box/view.html.php
Labels: 3.0.3, Improve, Ready for Merge

#5542 REDSHOP-6195 Create more filters by payment status and order status in Order Statistic
  component/admin/models/statistic_order.php
  component/admin/views/statistic_order/tmpl/default.php
  component/admin/views/statistic_order/view.html.php
  libraries/redshop/helper/order.php
Labels: 3.0.3, Improve, Ready for Merge, Scrutinizer fail

#5543 REDSHOP-6201 Filter customfield always "OR"
  libraries/redshop/helper/category.php
  libraries/redshop/helper/product.php
Labels: 3.0.3, Bug, Ready for Merge

#5497 REDSHOP-6156: Show error when user create item with Start > End field (Quantity, Date)
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/attributeprices_detail/tmpl/default.php
Labels: 3.0.3, Bug, Ready for Merge

#5534 REDSHOP-6202: Fix missing logo payment when enable sh404
  libraries/redshop/tags/sections/paymentmethod.php
Labels: 3.0.3, Bug, Ready for Merge

#5539 REDSHOP-6200 Update Joomla version 3.9.23
  RoboFile.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
Labels: QA automation

#5496 REDSHOP-6149: Can I make a gradual increase in discount.
  libraries/redshop/helper/discount.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Shipping/ShippingPostDanmark.php
  tests/acceptance/integration/g02/Manufacturer/CheckoutProductInManufacturerDetailCest.php
Labels: 3.0.3, Bug, Ready for Merge

#5520 REDSHOP-6188 Error query when enable "Force translate default language" in redcore
  component/site/models/category.php
  component/site/models/search.php
Labels: 3.0.3, Bug, Ready for Merge

#5540 REDSHOP-6114: Custom fields section payment not show frontend and when click radio payment, not show custom fields (if payment have custom fields)
  component/site/views/checkout/tmpl/onestepcheckout.php
  component/site/views/checkout/view.html.php
  libraries/redshop/src/Fields/SiteHelper.php
  libraries/redshop/tags/sections/onestepcheckout.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.3, Bug, Ready for Merge
