Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-05, with the labels that each got.

#5233 REDSHOP-5908: Discount calculator breaks with: Class 'Redshop\Promotion\RedshopHelperProductPrice' not found
  component/admin/views/product_detail/tmpl/default_calculator.php
  component/site/views/product/tmpl/default_calculator.php
  libraries/redshop/src/Promotion/Discount.php
Labels: 3.0.2, Conflict, Hot Fix

#5234 REDSHOP-5912: Refactor Libraries Redshop
  libraries/redshop/src/Currency/CurrencyLayer.php
  libraries/redshop/src/Economic/RedshopEconomic.php
  libraries/redshop/src/User/Helper.php
Labels: 3.0.2, Refactor, Wait for QA

#5323 Remove sh404sef url when delete a Manufacturer or Category
  component/admin/models/categories.php
  component/admin/models/manufacturers.php
  plugins/redshop_product/sh404urls/sh404urls.php
  plugins/redshop_product/sh404urls/sh404urls.xml
Labels: 3.0.2, Hot Fix

#5328 REDSHOP-5982 create code automation for Rating/review
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/ConfigurationPage.php
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/Administrator/RatingManagerPage.php
  tests/_support/Step/AbstractStep.php
  tests/acceptance.suite.yml.dist.drone
  tests/acceptance/administrator/_steps/Joomla3Steps/AdminManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CustomFieldManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/StockRoomManagerJoomla3Steps.php
  tests/acceptance/administrator/g04/Stockrooms/StockRoom/StockRoomCest.php
  tests/acceptance/administrator/g17/CustomerInput/RatingManagerCest.php
Labels: QA automation

#5331 [BEFR-442][Feature] Add options to login with Facebook or Google
  composer.json
  libraries/redshop/composer.json
  libraries/redshop/helper/joomla.php
  modules/site/mod_redshop_login/css/index.html
  modules/site/mod_redshop_login/helper.php
  modules/site/mod_redshop_login/images/index.html
  modules/site/mod_redshop_login/index.html
  modules/site/mod_redshop_login/js/index.html
  modules/site/mod_redshop_login/language/en-GB/en-GB.mod_redshop_login.ini
  modules/site/mod_redshop_login/language/en-GB/en-GB.mod_redshop_login.sys.ini
  modules/site/mod_redshop_login/language/en-GB/index.html
  modules/site/mod_redshop_login/language/index.html
  modules/site/mod_redshop_login/mod_redshop_login.php
  modules/site/mod_redshop_login/mod_redshop_login.xml
  modules/site/mod_redshop_login/tmpl/default.php
  modules/site/mod_redshop_login/tmpl/default_logout.php
  modules/site/mod_redshop_login/tmpl/index.html
  redGulp/extensions/modules/frontend/redshop_login.js
Labels: 3.0.2, Demo Code, Ready for Merge

#5335 Add event onDisplayTabMenu
  component/admin/views/product_detail/view.html.php
Labels: 3.0.2, Hot Fix

#5337 REDSHOP-5987: [Bug][TL-123][TL-124] Fix show / hide discontiued product
  libraries/redshop/helper/category.php
  libraries/redshop/helper/product.php
Labels: 3.0.2, Hot Fix

#5338 [KON-1084] Module redSHOP Switch VAT
  modules/site/mod_redshop_switch_vat/css/index.html
  modules/site/mod_redshop_switch_vat/helper.php
  modules/site/mod_redshop_switch_vat/images/index.html
  modules/site/mod_redshop_switch_vat/index.html
  modules/site/mod_redshop_switch_vat/js/default.js
  modules/site/mod_redshop_switch_vat/js/index.html
  modules/site/mod_redshop_switch_vat/language/en-GB/en-GB.mod_redshop_switch_vat.ini
  modules/site/mod_redshop_switch_vat/language/en-GB/en-GB.mod_redshop_switch_vat.sys.ini
  modules/site/mod_redshop_switch_vat/language/en-GB/index.html
  modules/site/mod_redshop_switch_vat/language/index.html
  modules/site/mod_redshop_switch_vat/mod_redshop_switch_vat.php
  modules/site/mod_redshop_switch_vat/mod_redshop_switch_vat.xml
  modules/site/mod_redshop_switch_vat/tmpl/default.php
  modules/site/mod_redshop_switch_vat/tmpl/index.html
  redGulp/extensions/modules/frontend/redshop_switch_vat.js
Labels: 3.0.2, Feature

#5336 TL-121 Products in same catogory being shown differently
  libraries/redshop/helper/category.php
Labels: 3.0.2, Hot Fix

#5333 REDSHOP-5981 Create codeception for question
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/Administrator/OrderManagerPage.php
  tests/_pages/Joomla3/Administrator/QuestionManagerJoomla3Page.php
  tests/acceptance/administrator/Oder_Backend/OrderDiscount/OrderDiscountAndSpecialUpdateCest.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CategoryManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CategorySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderUpdateDiscountAndSpecialDiscountSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductUpdateOnQuantitySteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuestionManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/RatingManagerSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/UserManagerJoomla3Steps.php
  tests/acceptance/administrator/g17/CustomerInput/QuestionManagerCest.php
  tests/acceptance/integration/g17/Plugins/Shipping/shippingDefaultGLSCest.php
Labels: Codeception, QA automation

#5340 REDSHOP-5973 Show tag {redshop:numberproduct} in module
  libraries/redshop/tags/sections/product.php
Labels: 3.0.2, Hot Fix

#5341 REDSHOP-5951 Show error when user Add Cart with change config NO
  libraries/redshop/src/Traits/Replace/CartItem.php
Labels: 3.0.2, Hot Fix, Merged

#5342 REDSHOP-5946 add cart button not same other page
  component/site/views/account/tmpl/mytags.html.twig
Labels: 3.0.2, Bug, Ready for Merge

#5345 REDSHOP-5965 Postdanmark plugin > Checkout shipping address on order reciept email
  component/site/models/checkout.php
Labels: 3.0.2, Hot Fix

#5346 REDSHOP-5906 Template (backend) - Filter status not work
  component/admin/models/templates.php
  name
  nano.save
  template_desc
Labels: 3.0.2, Bug, Ready for Merge

#5351 Change varible
  component/site/models/category.php
Labels: 3.0.2, Hot Fix, Merged

#5339 REDSHOP-5986: [Feature] Tax rate with level Shopper Group
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/models/forms/tax_rate.xml
  component/admin/models/tax_rate.php
  component/admin/models/tax_rates.php
  component/admin/sql/install/mysql/install.sql
  component/admin/sql/install/mysql/uninstall.sql
  component/admin/sql/updates/mysql/3.0.2.sql
  component/admin/tables/tax_rate.php
  component/admin/views/tax_rates/view.html.php
  component/site/controllers/checkout.php
  component/site/layouts/fields/html.php
  component/site/models/checkout.php
  libraries/redshop/entity/tax_rate.php
  libraries/redshop/helper/tax.php
  libraries/redshop/helper/user.php
  libraries/redshop/src/Cart/Helper.php
  libraries/redshop/src/Fields/SiteHelper.php
  libraries/redshop/src/Template/Helper.php
  redshop.xml
  tests/_pages/Joomla3/Administrator/TaxRatePage.php
  tests/acceptance/administrator/Oder_Backend/OrderBackendProductAttribute/OderBackendWithForeignCountryCest.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/TaxRateSteps.php
  tests/acceptance/administrator/g11/Products/Tax_Rate/TaxRateCest.php
  tests/acceptance/integration/g10/Product_Attribute/AttributeUserCest.php
  tests/acceptance/integration/g13/VAT/CheckVATChangedDependingOnTheUserCest.php
  tests/acceptance/integration/g13/VAT/ProductAttributesVatCheckoutCest.php
  tests/acceptance/integration/g13/VAT/ProductVatCheckoutCest.php
Labels: 3.0.2, Merged, Ready for Merge
