Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-04, with the labels that each got.

#5286 REDSHOP-5953: [Refactor][Performance] Create Performance Library for redSHOP
  component/admin/config/config.dist.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/configuration/tmpl/default_performance.php
  component/admin/views/configuration/view.html.php
  libraries/redshop/src/Config/App.php
  libraries/redshop/src/Performance/Helper.php
Labels: 3.0.1, Refactor

#5288 Release redSHOP 3.0.1
  README.md
  component/admin/tables/attributeprices_detail.php
  component/site/views/account/view.html.php
  libraries/redshop/src/Account/Helper.php
  libraries/redshop/src/Attribute/Helper.php
  libraries/redshop/src/Catalog/Catalog.php
  libraries/redshop/src/Catalog/Sample.php
  libraries/redshop/src/Manufacturer/Helper.php
  libraries/redshop/src/Performance/Helper.php
  libraries/redshop/src/Promotion/Coupon.php
  libraries/redshop/src/Stock/Helper.php
  libraries/redshop/src/Traits/Replace/Product.php
  libraries/redshop/src/Wishlist/Helper.php
  libraries/redshop/tags/abstract.php
  libraries/redshop/tags/sections/account.php
  libraries/redshop/tags/sections/category.php
  libraries/redshop/tags/sections/categorydetail.php
  libraries/redshop/tags/sections/categoryproduct.php
  libraries/redshop/tags/sections/clicktellsms.php
  libraries/redshop/tags/sections/manufacturerdetail.php
  libraries/redshop/tags/sections/manufacturerproduct.php
  libraries/redshop/tags/sections/orderlist.php
  libraries/redshop/tags/sections/product.php
  libraries/redshop/tags/sections/productsample.php
  libraries/redshop/tags/sections/quotationdetail.php
  libraries/redshop/tags/sections/quotationrequest.php
  libraries/redshop/tags/sections/relatedproduct.php
  libraries/redshop/tags/sections/wishlist.php
  libraries/redshop/view/view.php
  redshop.xml
Labels: 3.0.1, Release Version

#5285 REDSHOP-5952: [Refactor][SQL] Admin/Models/User_Detail
  component/admin/models/user_detail.php
  component/admin/views/user_detail/tmpl/default_billing.php
  component/admin/views/user_detail/tmpl/default_shipping.php
  component/admin/views/user_detail/view.html.php
  libraries/redshop/helper/user.php
  libraries/redshop/src/User/Helper.php
Labels: 3.0.2, Ready for Merge, Refactor

#5291 Fix replace tag before event onReplaceShippingTemplate
  component/site/controllers/checkout.php
  libraries/redshop/tags/sections/shippingmethod.php
Labels: 3.0.2, Hot Fix

#5292 Hotfix conflict css between bootstrap 4 and bootstrap 3 default by redSHOP
  component/site/layouts/assets.php
Labels: 3.0.2, Hot Fix

#5294 [Refactor][Feature] Ability to change Payment method of exist orders in backend
  component/admin/controllers/order_detail.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/order_detail/tmpl/default.php
  component/admin/views/order_detail/tmpl/default_payment.php
  libraries/redshop/src/Order/Helper.php
Labels: 3.0.2, Ready for Merge, Refactor

#5295 REDSHOP-5958: [Refactor][Feature] Send order payment method change email for notify customer when update payment method
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/site/language/en-GB/en-GB.com_redshop.ini
  libraries/redshop/layouts/email/order/payment_method_changed.php
  libraries/redshop/src/Order/Helper.php
Labels: 3.0.2, Refactor, Wait for QA

#5293 REDSHOP-5956 Write codeception for module redshop related product
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/System/ModuleManagerJoomlaPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Administrator/Module/ModuleManagerJoomla.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/Module/ModuleProductRelatedSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/TaxRateSteps.php
  tests/acceptance/integration/g08/Compare_Products/CompareProductsCest.php
  tests/acceptance/integration/g17/Module/ModuleProductRelatedCest.php
Labels: QA automation

#5296 REDSHOP-5961 Broken layout when product detail enable 'Product Discontinued'
  libraries/redshop/src/Cart/Render.php
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.2, Bug, Wait for QA

#5311 REDSHOP-5967: [Feature][TL-109] Configuration that show / hide discountinued products at FE
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/configuration/tmpl/default_product_general.php
  component/admin/views/configuration/view.html.php
  component/site/models/category.php
  libraries/redshop/src/Config/App.php
Labels: 3.0.2, Feature, Wait for QA

#5312 REDSHOP-5968 codeception for product Discount but show on frontend
  tests/_pages/Joomla3/Administrator/ConfigurationPage.php
  tests/_pages/Joomla3/Administrator/ProductManagerPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CategoryManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ProductsConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductManagerJoomla3Steps.php
  tests/acceptance/administrator/g07/Configuration/ConfigurationShowDiscontinuedProductsCest.php
Labels: QA automation

#5299 Remove unnecessary div
  libraries/redshop/helper/product/tag.php
Labels: 3.0.2, Hot Fix, Merged

#5313 REDSHOP-5966: Admin > Product detail view > SEO > Canonical Url
  component/admin/views/product_detail/tmpl/default_product_meta_data.php
Labels: 3.0.2, External, Wait for QA

#5316 REDSHOP-5970:[Feature] New sorting option for redSHOP category view - random sorting - and also check box to place out of stock products after in stock products
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/configuration/tmpl/default_product_template_image_settings.php
  component/admin/views/configuration/view.html.php
  component/site/language/en-GB/en-GB.com_redshop.ini
  component/site/models/category.php
  libraries/redshop/helper/product/tag.php
  libraries/redshop/helper/utility.php
  libraries/redshop/src/Config/App.php
Labels: 3.0.2, Feature, Wait for QA

#5315 REDSHOP-5969 Open 3 Cest on folder Fail random
  tests/_pages/Joomla3/Administrator/AdminJ3Page.php
  tests/_pages/Joomla3/Administrator/OrderManagerPage.php
  tests/_pages/Joomla3/System/ModuleManagerJoomlaPage.php
  tests/acceptance/__disabled/checkout/ProductsCheckoutAuthorizeCest.php
  tests/acceptance/__disabled/checkout/ProductsCheckoutStripeCest.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CouponSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
  tests/acceptance/install/core/InstallRedShopCest.php
  tests/acceptance/integration/__disabled/Products/ProductsCheckoutFrontEndCest.php
  tests/acceptance/integration/g05/Stockroom/CheckoutWithStockroomCest.php
  tests/acceptance/integration/g10/Discounts/GiftCardCheckout/GiftCardCheckoutProductCest.php
  tests/acceptance/integration/g10/Products/ProductsCheckoutFrontEndCest.php
  tests/acceptance/integration/g17/Module/ModuleMultiCurrenciesCest.php
  tests/acceptance/integration/g17/Plugins/payment/CheckoutWithSKRILLPaymentCest.php
  tests/acceptance/integration/g17/Plugins/payment/ProductsCheckoutStripePaymentCest.php
Labels: QA automation

#5320 [Hot fix] Fix for mod_redshop_related_products
  libraries/redshop/helper/product.php
Labels: 3.0.2, Hot Fix

#5297 [Fix] The price is changed to without VAT after addtocart
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
Labels: 3.0.2, Bug, Ready for Merge

#5298 TL-68 Display character some detele a product on cart module
  component/site/layouts/cart/cart.php
  modules/site/mod_redshop_cart/js/cart.js
Labels: 3.0.2, Bug, Ready for Merge

#5317 MEDPACK-123 add event 'onRenderBillingCheckout'
  component/site/controllers/registration.php
Labels: 3.0.2, Improve, Ready for Merge

#5322 REDSHOP-5975 Update joomla version 3.9.18 for redSHOP
  RoboFile.php
Labels: Ready for Merge

#5325 REDSHOP-5976 Codeception for product in redSHOP Config
  tests/_pages/Joomla3/Administrator/ConfigurationPage.php
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Configuration/ProductsConfigurationSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/Frontend/payment/CheckoutWithStripePayment.php
  tests/acceptance/administrator/g07/Configuration/ProductsConfigurationCest.php
  tests/acceptance/integration/g10/Discounts/GiftCardCheckout/GiftCardCheckoutProductCest.php
Labels: QA automation

#5327 REDSHOP-5098: Product: Media media_mimetype is not detect if image was uploaded via main upload form
  component/admin/models/category.php
  component/admin/models/product_detail.php
Labels: 3.0.2

#5329 [Support Automation] add name for iframe
  libraries/redshop/layouts/tags/common/modal.html.twig
  libraries/redshop/tags/sections/product.php
Labels: 3.0.2, Hot Fix
