Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2020-03, with the labels that each got.

#5198 REDSHOP-5875 Cart Settings- Quantity change in cart Choose No - Display quantity not correct
  libraries/redshop/src/Traits/Replace/CartItem.php
Labels: 3.0.1, Bug, Drone fail

#5206 REDSHOP-5884 Support Automation for redSHOP 3.0.1
  .drone.yml
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/_pages/Joomla3/Administrator/ProductManagerPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
Labels: QA automation

#5205 REDSHOP-5882 Wrong price when have preselected attribute
  libraries/redshop/helper/product.php
  libraries/redshop/helper/product_attribute.php
  libraries/redshop/tags/sections/attributes.php
  tests/_pages/Joomla3/Administrator/OrderManagerPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ProductCheckoutManagerJoomla3Steps.php
Labels: 3.0.1, Bug, Ready for Merge

#5208 RT-93 Validate field username, password when config normal account creation
  media/com_redshop/js/redshop.registration.js
  media/com_redshop/js/redshop.registration.min.js
  src/assets/com_redshop/js/redshop.registration.js
Labels: 3.0.1, Bug, Ready for Merge

#5216 REDSHOP-5892 Add config set page format for plugin tcpdf
  plugins/redshop_pdf/tcpdf/language/en-GB/en-GB.plg_redshop_pdf_tcpdf.ini
  plugins/redshop_pdf/tcpdf/tcpdf.php
  plugins/redshop_pdf/tcpdf/tcpdf.xml
Labels: 3.0.1, Bug, Ready for Merge

#5204 REDSHOP-5670 [Refactor] - Tags System - Refactoring Code - Template section: Category
  component/site/views/category/tmpl/detail.php
  libraries/redshop/layouts/tags/addtocart/template.html.twig
  libraries/redshop/layouts/tags/category/filter_form.html.twig
  libraries/redshop/layouts/tags/category/orderby_form.html.twig
  libraries/redshop/layouts/tags/category/price_slider.html.twig
  libraries/redshop/layouts/tags/category/template_selecter_form.html.twig
  libraries/redshop/layouts/tags/common/link.html.twig
  libraries/redshop/src/Product/Image/Render.php
  libraries/redshop/tags/sections/category.php
  libraries/redshop/tags/sections/categorydetail.php
Labels: 3.0.1, Drone fail, Refactor

#5212 REDSHOP-5750 [Refactor] - Tags System - Refactoring Code - Template section: Quotation Request Template
  component/site/views/quotation/tmpl/default.php
  libraries/redshop/layouts/tags/quotation_request/cancel_btn.html.twig
  libraries/redshop/layouts/tags/quotation_request/request_quotation_btn.html.twig
  libraries/redshop/tags/sections/quotationrequest.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.1, Drone fail, Refactor, Scrutinizer fail

#5214 RT-99 Order final - Not show VAT price in cart
  libraries/redshop/helper/tax.php
Labels: 3.0.1, Bug, Drone fail, Merged

#5210 REDSHOP-5889 [Bug] Error in product view with product have attribute set
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.1, Bug, Drone fail

#5207 REDSHOP-5756: [Refactor] - Tags System - Refactoring Code - Template section: Clickatell SMS
  component/site/models/checkout.php
  libraries/redshop/helper/clickatell.php
  libraries/redshop/tags/sections/clicktellsms.php
Labels: 3.0.1, Merged, Refactor

#5218 REDSHOP-5877: Cannot add to cart when enabel SEO
  libraries/redshop/layouts/tags/addtocart/link.html.twig
  libraries/redshop/src/Cart/Render.php
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.1, Hot Fix, Ready for Merge

#5211 REDSHOP-5890 [Bug] Load all orders in newest order section administrator
  libraries/redshop/src/Order/Helper.php
Labels: 3.0.1, Bug, Drone fail, Merged

#5209 REDSHOP-5888 [Bug] Error "missing-input-response" in registration user
  component/site/models/registration.php
Labels: 3.0.1, Bug, Merged

#5220 REDSHOP-5715: Missing message after click on "Save" button
  component/admin/controllers/stockroom_listing.php
  component/admin/language/en-GB/en-GB.com_redshop.ini
Labels: 3.0.1, Bug, Drone fail

#5221 REDSHOP-5905: Registration page - Password/Confirm password not show "*" when user input type
  libraries/redshop/tags/sections/billingtemplate.php
Labels: 3.0.1, Bug, Ready for Merge

#5217 [Enhancement] \Redshop\DB\Tool class
  libraries/redshop/src/DB/Tool.php
  package-lock.json
Labels: 3.0.1, Hot Fix, QA before release

#5224 REDSHOP-5911 Update joomla version 3.9.16 for redSHOP
  RoboFile.php
Labels: QA automation

#5229 REDSHOP-5815 [Refactor] - Enhancement REDSHOP-5683
  libraries/redshop/tags/sections/changecartattribute.php
Labels: 3.0.1, Wait for QA

#5231 Remove function deprecated
  libraries/redshop/helper/cart/tag.php
Labels: 3.0.1, QA before release, Refactor

#5228 REDSHOP-5894 [Refactor] - Tags System - Refactoring Code - Template section: Product
  component/site/language/en-GB/en-GB.com_redshop.ini
  component/site/models/product.php
  component/site/views/product/tmpl/default.php
  component/site/views/product_rating/tmpl/default.php
  libraries/redshop/helper/product.php
  libraries/redshop/layouts/tags/manufacturer/image.html.twig
  libraries/redshop/layouts/tags/product/bookmark.html.twig
  libraries/redshop/layouts/tags/product/category_list.html.twig
  libraries/redshop/layouts/tags/product/facebook_like_button.html.twig
  libraries/redshop/layouts/tags/product/heading.html.twig
  libraries/redshop/layouts/tags/product/more_document.html.twig
  libraries/redshop/layouts/tags/product/more_image.html.twig
  libraries/redshop/layouts/tags/product/more_image/lightbox.html.twig
  libraries/redshop/layouts/tags/product/more_image/without_lightbox.html.twig
  libraries/redshop/layouts/tags/product/more_videos.html.twig
  libraries/redshop/layouts/tags/product/my_tags_button.html.twig
  libraries/redshop/layouts/tags/product/size.html.twig
  libraries/redshop/layouts/tags/product/subscription.html.twig
  libraries/redshop/layouts/tags/product/thumb_image.html.twig
  libraries/redshop/layouts/tags/product/zoom_image.html.twig
  libraries/redshop/src/Product/Product.php
  libraries/redshop/src/Product/Stock.php
  libraries/redshop/tags/abstract.php
  libraries/redshop/tags/sections/accessory.php
  libraries/redshop/tags/sections/account.php
  libraries/redshop/tags/sections/manufacturer.php
  libraries/redshop/tags/sections/product.php
  libraries/redshop/tags/sections/wishlist.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.1, Drone fail, Refactor, Scrutinizer fail

#5235 REDSHOP-5910 Duplicate product when user install latest code
  libraries/redshop/tags/sections/categorydetail.php
Labels: 3.0.1, Bug, Drone fail, Scrutinizer fail

#5223 REDSHOP-5903: Add attribute from attribute set it show 1 attribute item
  component/admin/views/product_detail/tmpl/default_product_attribute.php
Labels: 3.0.1, Bug, Merged

#5237 REDSHOP-5678 [Refactor] - Tags System - Refactoring Code - Template section: Account Tempate
  component/site/models/account.php
  component/site/views/account/tmpl/default.php
  libraries/redshop/helper/order.php
  libraries/redshop/layouts/tags/account/logout_link.html.twig
  libraries/redshop/src/Account/Helper.php
  libraries/redshop/src/Newsletter/Tag.php
  libraries/redshop/src/Promotion/Coupon.php
  libraries/redshop/src/Traits/Replace/NewsletterSubscription.php
  libraries/redshop/src/Wishlist/Helper.php
  libraries/redshop/tags/sections/account.php
  media/com_redshop/templates/account_template/default.php
Labels: 3.0.1, Refactor, Wait for QA

#5227 REDSHOP-5907: Search module -Show error when user fill in " " then click on search icon
  component/site/models/search.php
Labels: 3.0.1, Bug, Drone fail, Merged, Scrutinizer fail

#5246 Gulp 4 hot fix for gulp copy
  gulpfile.js
  media/com_redshop/js/ajaxupload.min.js
  media/com_redshop/js/media.min.js
  media/com_redshop/js/redshop.admin.common.min.js
  media/com_redshop/js/redshop.admin.media.min.js
  media/com_redshop/js/redshop.admin.min.js
  media/com_redshop/js/redshop.alert.min.js
  media/com_redshop/js/redshop.attribute-manipulation.min.js
  media/com_redshop/js/redshop.attribute.min.js
  media/com_redshop/js/redshop.common.min.js
  media/com_redshop/js/redshop.creditcard.min.js
  media/com_redshop/js/redshop.fields.min.js
  media/com_redshop/js/redshop.inline.min.js
  media/com_redshop/js/redshop.layout.min.js
  media/com_redshop/js/redshop.media.min.js
  media/com_redshop/js/redshop.min.js
  media/com_redshop/js/redshop.onestep.min.js
  media/com_redshop/js/redshop.order.min.js
  media/com_redshop/js/redshop.redbox.min.js
  media/com_redshop/js/redshop.registration.min.js
  media/com_redshop/js/redshop.search.min.js
  media/com_redshop/js/redshop.thumbscroller.min.js
  media/com_redshop/js/redshop.utils.min.js
  media/com_redshop/js/redshop.validation.min.js
  media/com_redshop/js/redshop.wishlist.min.js
  media/com_redshop/js/redshop.xmlfunc.min.js
  package-lock.json
  package.json
  redGulp/extensions/components/redshop.assets.js
  redGulp/extensions/components/redshop.js
  redGulp/extensions/helpers/plugin.js
  redGulp/extensions/libraries/redshop.js
  redGulp/src/6.plugins.js
  redGulp/src/8.composer.js
  redGulp/src/main.js
  redGulp/tasks/release/modules.js
  redGulp/tasks/release/plugins.js
Labels: 3.0.1, Hot Fix

#5248 [Hot fix] Gulp copy backend language
  redGulp/extensions/components/redshop.js
Labels: 3.0.1, Hot Fix, Merged

#5241 REDSHOP-5918 [Refactor] - Tags System - Refactoring Code - Template section: Manufacturer Product
  component/site/views/manufacturers/tmpl/products.php
  libraries/redshop/layouts/tags/common/pageheading.html.twig
  libraries/redshop/layouts/tags/manufacturer_product/filter_by.html.twig
  libraries/redshop/layouts/tags/manufacturer_product/order_by.html.twig
  libraries/redshop/src/Traits/Replace/Product.php
  libraries/redshop/tags/abstract.php
  libraries/redshop/tags/sections/manufacturerproduct.php
Labels: 3.0.1, Merged, Refactor, Scrutinizer fail

#5244 REDSHOP-5921 [Refactor] - Tags System - Refactoring Code - Template section: Manufacturer detail
  component/site/models/manufacturers.php
  component/site/views/manufacturers/tmpl/detail.php
  libraries/redshop/src/Manufacturer/Helper.php
  libraries/redshop/tags/sections/manufacturerdetail.php
Labels: 3.0.1, Merged, Refactor, Scrutinizer fail

#5249 REDSHOP-5730: Add message when user click "Start Export" but not select item
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/export/tmpl/default.php
Labels: 3.0.1, Bug, Merged

#5252 REDSHOP-5868: Language is wrong when user hover on text
  component/admin/language/en-GB/en-GB.com_redshop.ini
Labels: 3.0.1, Hot Fix, Merged

#5250 REDSHOP-5923 [Refactor] - Tags System - Refactoring Code - Template section: Product sample
  component/site/language/en-GB/en-GB.com_redshop.ini
  component/site/models/catalog.php
  component/site/views/catalog/tmpl/default.php
  component/site/views/catalog/tmpl/sample.php
  libraries/redshop/layouts/tags/product_sample/form.html.twig
  libraries/redshop/layouts/tags/product_sample/sample.html.twig
  libraries/redshop/src/Catalog/Catalog.php
  libraries/redshop/src/Catalog/Sample.php
  libraries/redshop/tags/sections/catalog.php
  libraries/redshop/tags/sections/product.php
  libraries/redshop/tags/sections/productsample.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
Labels: 3.0.1, Merged, Refactor

#5251 REDSHOP-5934: [Hot fix] fix template frontend category not show when template has not tag
  libraries/redshop/tags/sections/categoryfrontpage.php
Labels: 3.0.1, Drone fail, Hot Fix, Merged

#5245 REDSHOP-5891: Module REDSHOP-Product/Missing Add to cart button and show error when Enable cart ajax
  libraries/redshop/src/Cart/Render.php
Labels: 3.0.1, Bug, Drone fail, Merged

#5253 REDSHOP-5925 [Refactor] - Tags System - Refactoring Code - Template section: Order list
  component/site/views/orders/tmpl/default.php
  libraries/redshop/layouts/tags/common/div_link.html.twig
  libraries/redshop/layouts/tags/order_list/pagination_limit.html.twig
  libraries/redshop/tags/abstract.php
  libraries/redshop/tags/sections/orderlist.php
Labels: 3.0.1, Refactor, Scrutinizer fail

#5243 REDSHOP-5778 [Bug] Fix bug of Wrapper
  component/admin/models/wrapper.php
  libraries/redshop/tags/sections/wrapper.php
  media/com_redshop/js/redshop.attribute.js
  media/com_redshop/js/redshop.attribute.min.js
  src/assets/com_redshop/js/redshop.attribute.js
Labels: 3.0.1, Bug, Drone fail, Merged, Scrutinizer fail

#5256 REDSHOP-5915 Checkout Shipping modal popup errors
  libraries/redshop/layouts/tags/shipping_address/userinfo.html.twig
Labels: 3.0.1, Bug, Merged

#5239 REDSHOP-5713: Create Quotation missing Country
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/views/addquotation_detail/tmpl/default.php
  component/admin/views/quotation/tmpl/default.php
Labels: 3.0.1, Bug, Conflict, Drone fail

#5230 REDSHOP-5714: Message create Mail not meaning when not select Mail sestion
  libraries/redshop/form/field/mail_section.php
  libraries/redshop/helper/template.php
  name
  template_desc
Labels: 3.0.1, Bug, Drone fail, Merged

#5242 REDSHOP-5807: Accept Terms & conditions For Webshop - Not display error when User not accept
  libraries/redshop/layouts/tags/checkout/button.html.twig
  libraries/redshop/tags/sections/commondisplaycart.php
  media/com_redshop/js/redshop.common.js
  media/com_redshop/js/redshop.common.min.js
  src/assets/com_redshop/js/redshop.common.js
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutMissingData.php
Labels: 3.0.1, Bug, Ready for Merge

#5254 REDSHOP-5916 File upload does not respect allowed file ext from RS config
  component/site/controllers/product.php
Labels: 3.0.1, Bug, Merged

#5259 REDSHOP-5932: Wrapping - New version not same with redSHOP 2.1.5
  component/admin/models/wrapper_detail.php
Labels: 3.0.1, Bug, Ready for Merge

#5247 REDSHOP-5736: Add "Save" button in page detail
  component/admin/controllers/rating_detail.php
  component/admin/models/rating_detail.php
  component/admin/views/rating_detail/tmpl/default.php
  component/admin/views/rating_detail/view.html.php
Labels: 3.0.1, Bug, Drone fail, Merged, Scrutinizer fail

#5203 REDSHOP-5775: [Refactor] - Tags System - Refactoring Code - Template section: Wishlist
  component/admin/layouts/templates/template_tag.php
  component/site/models/wishlist.php
  component/site/views/wishlist/tmpl/viewwishlist.php
  libraries/redshop/layouts/tags/wishlist/template.html.twig
  libraries/redshop/tags/sections/wishlist.php
Labels: 3.0.1, Drone fail, Merged, Refactor, Scrutinizer fail

#5255 REDSHOP-5731: Missing popup question before delete item
  component/admin/redshop.php
  component/admin/views/attribute_set/tmpl/default.php
  component/admin/views/attributeprices/tmpl/default.php
  component/admin/views/media/tmpl/default.php
  component/admin/views/newsletter/tmpl/default.php
  component/admin/views/newslettersubscr/tmpl/default.php
  component/admin/views/prices/tmpl/default.php
  component/admin/views/quotation/tmpl/default.php
  component/admin/views/sample/tmpl/default.php
  component/admin/views/shipping_rate/tmpl/default.php
  component/admin/views/stockimage/tmpl/default.php
  component/admin/views/stockroom/tmpl/default.php
  component/admin/views/wrapper/tmpl/default.php
  media/com_redshop/js/redshop.admin.js
  media/com_redshop/js/redshop.admin.min.js
  src/assets/com_redshop/js/redshop.admin.js
Labels: 3.0.1, Bug, Drone fail, Merged

#5263 REDSHOP-5927 [Refactor] - Tags System - Refactoring Code - Template section: Quotation detail
  component/site/views/quotation_detail/tmpl/default.php
  component/site/views/quotation_detail/view.html.php
  libraries/redshop/layouts/tags/quotation/cancel_btn.html.twig
  libraries/redshop/layouts/tags/quotation/request_quotation_btn.html.twig
  libraries/redshop/layouts/tags/quotation/status.html.twig
  libraries/redshop/src/Traits/Replace/Product.php
  libraries/redshop/tags/sections/manufacturerproduct.php
  libraries/redshop/tags/sections/quotationdetail.php
  libraries/redshop/tags/sections/quotationrequest.php
  media/com_redshop/templates/quotation_detail/default.php
Labels: 3.0.1, Drone fail, Refactor, Scrutinizer fail

#5264 REDSHOP-5935: Quotation backend - Show tag html in Wrapping field
  component/admin/controllers/addquotation_detail.php
  component/admin/models/addquotation_detail.php
  libraries/redshop/helper/product.php
  libraries/redshop/helper/product/tag.php
Labels: 3.0.1, Bug, Drone fail, Scrutinizer fail

#5265 REDSHOP-5933: Checkout missing field required different between 2.1.5 and 3.0.0
  libraries/redshop/tags/sections/commonfield.php
Labels: 3.0.1, Drone fail, Hot Fix

#5268 REDSHOP-5775: Fix Automation Wishlist
  libraries/redshop/layouts/tags/wishlist/template.html.twig
  tests/_pages/Joomla3/Administrator/WishListPage.php
Labels: 3.0.1, Bug, Wait for QA

#5270 REDSHOP-5775 Change xpath support automation for wishlist
  tests/_pages/Joomla3/Administrator/WishListPage.php
  tests/acceptance/administrator/_steps/Joomla3Steps/QuotationManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/ShippingSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/StockImageSteps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/StockRoomManagerJoomla3Steps.php
  tests/acceptance/administrator/_steps/Joomla3Steps/WrapperSteps.php
Labels: 3.0.1, QA automation

#5271 REDSHOP-5914 [Refactor] Twig for Site/Account/MyTags
  component/site/models/account.php
  component/site/views/account/tmpl/mytags.html.twig
  component/site/views/account/tmpl/mytags.php
  component/site/views/account/view.html.php
  libraries/redshop/layouts/tags/addtocart/addtocartscroll.html.twig
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutChangeQuantityProductSteps.php
Labels: 3.0.1, Merged, Refactor

#5258 REDSHOP-5926 [Refactor] - Tags System - Refactoring Code - Template section: Related product
  component/site/views/product/tmpl/default_related.php
  libraries/redshop/layouts/tags/related_product/relproduct_image.html.twig
  libraries/redshop/tags/sections/relatedproduct.php
Labels: 3.0.1, Ready for Merge, Refactor

#5269 REDSHOP-5924 [Refactor] - Tags System - Refactoring Code - Template section: Category product
  component/site/layouts/general/print.php
  component/site/views/category/tmpl/categoryproduct.php
  libraries/redshop/layouts/tags/category_product/hidden_user_field.html.twig
  libraries/redshop/layouts/tags/category_product/page_heading.html.twig
  libraries/redshop/layouts/tags/category_product/selector_category.html.twig
  libraries/redshop/layouts/tags/category_product/thumb_image.html.twig
  libraries/redshop/src/Product/Product.php
  libraries/redshop/tags/sections/categoryproduct.php
  tests/acceptance/administrator/_steps/Joomla3Steps/OrderPaymentDiscountAndSpecialDiscountSteps.php
Labels: 3.0.1, Refactor, Wait for QA

#5272 [Refactor] [SQL] Admin/Table/AttributePrices_Detail
  component/admin/tables/attributeprices_detail.php
  libraries/redshop/src/Attribute/Helper.php
Labels: 3.0.1, Refactor, Scrutinizer fail

#5274 REDSHOP-5940 Show error when user click on Tag from Account Template
  component/site/models/account.php
  component/site/views/account/tmpl/mytags.html.twig
  component/site/views/account/view.html.php
  libraries/redshop/layouts/tags/addtocart/addtocartscroll.html.twig
  libraries/redshop/src/Promotion/Discount.php
Labels: 3.0.1, Bug, Merged

#5276 REDSHOP-5937: Add to cart. choose subproperty display error message
  libraries/redshop/src/Attribute/Helper.php
Labels: 3.0.1, Bug, Wait for QA

#5281 BEFR-347 Add event onDispalyText
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.1, Merged, Refactor

#5273 REDSHOP-5943: [Hot fix] Return false when has Accessory Product
  libraries/redshop/src/Cart/Cart.php
  tests/_pages/Joomla3/Administrator/FrontEndProductManagerJoomla3Page.php
  tests/acceptance/administrator/_steps/Joomla3Steps/CheckoutOnFrontEnd.php
Labels: 3.0.1, Hot Fix, Ready for Merge

#5278 REDSHOP-5947 [Reractor][Component][Site] Move to use Twig for view Account billto
  component/site/views/account_billto/tmpl/default.html.twig
  component/site/views/account_billto/tmpl/default.php
  component/site/views/account_billto/view.html.php
  media/com_redshop/js/account/billto.js
  media/com_redshop/js/account/billto.min.js
  src/assets/com_redshop/js/account/billto.js
Labels: 3.0.1, Ready for Merge, Refactor

#5275 REDSHOP-5945 [Reractor][Component][Site] Move to use Twig for view Account
  component/site/views/account/tmpl/cards.html.twig
  component/site/views/account/tmpl/cards.php
  component/site/views/account/tmpl/default.html.twig
  component/site/views/account/tmpl/default.php
  component/site/views/account/tmpl/mywishlist.html.twig
  component/site/views/account/tmpl/mywishlist.php
  component/site/views/account/view.html.php
  libraries/redshop/tags/sections/wishlist.php
  libraries/redshop/view/view.php
Labels: 3.0.1, Ready for Merge, Refactor

#5283 [REDSHOP-5950] [BEFR-347] Fix case add to cart have accessory out of stock
  component/site/language/en-GB/en-GB.com_redshop.ini
  libraries/redshop/src/Cart/Cart.php
  libraries/redshop/src/Stock/Helper.php
  libraries/redshop/tags/sections/addtocart.php
Labels: 3.0.1, Bug, Ready for Merge

#5267 REDSHOP-5913: Category back image not working.
  component/admin/language/en-GB/en-GB.com_redshop.ini
  component/admin/layouts/templates/template_tag.php
  libraries/redshop/tags/sections/category.php
Labels: 3.0.1, Bug, Wait for QA

#5284 Add event onAfterSaveCategory
  component/admin/tables/category.php
  libraries/redshop/table/nested.php
Labels: 3.0.1, Merged, Refactor
