Repository redCOMPONENT-COM/redSHOP, pull requests merged in 2022-07, with the labels that each got.

#5599 MEMI-105: fix custom field document delete first item
  libraries/redshop/helper/extrafields.php
Labels: Bug, 3.0.3

#5568 LAC-211: move js onestep checkout
  component/site/views/checkout/tmpl/onestepcheckout.php
  media/com_redshop/js/redshop.onestep.js
  media/com_redshop/js/redshop.onestep.min.js
  src/assets/com_redshop/js/redshop.onestep.js
Labels: Bug, 3.0.3

#5556 LAC-140: checkout with payment paypal, when callback url display page 404
  component/site/views/order_detail/view.html.php
Labels: Bug, 3.0.2

#5554 [Fix] wrong value of user's phone in order view pdf (admin)
  component/admin/views/order_detail/view.pdf.php
Labels: 3.0.3
